
RunTime: 5                
Debug: False

TcpGroups: 
- Name: group1           
  MaxTcpConnPerIP: 10000            #每个源IP创建最大TCP连接数
  SrcIP: ["2.0.0.19","2.0.0.100" ]  #源IP,为[]表示使用默认IP
  MaxQps: 500                       #发送http请求最大QPS 
  Dst: 2.0.0.67:80                  #TCP目的地址
  ReqThread: 10                     #发送http请求的线程数
  MaxReqest: 100                    #每个TCP连接最多发送多少连接
  IsHttps: false                    #是否是https
  SendHttp: ["test1"]               #每个TCP连接中循环发送的http请求

Params: 
- Name: aaa
  Type: RandomInt
  Spec: [1,10]
- Name: bbb
  Type: RandomStr
  Spec: [10]

HTTPConfs:
- Name: test1
  Proto: HTTP/1.1
  Method: GET
  URI: http://2.0.0.67?a=${foo}${str}
  Header: {
    "test":"faf"
  }
  Body: ""
  FileUpload: ""
  UseParams: ["aaa","bbb"]


